# Docker Compose configuration for SDLC Tools Semantic Search Chatbot
services:
  chatbot:
    # Build the Docker image from current directory
    build: .
    
    # Port mapping: host:container
    # Maps localhost:8080 to container port 8080 (Gradio default)
    ports:
      - "8080:8080"
    
    # Volume mounts for data persistence
    # Maps local ./data directory to container /app/data (read-only for safety)
    # This allows adding/updating data files without rebuilding the image
    volumes:
      - ./data:/app/data:ro
    
    # Environment variables for the container
    environment:
      # Ensure Python output is not buffered (better for logging)
      - PYTHONUNBUFFERED=1
      # Prevent Python from writing .pyc files
      - PYTHONDONTWRITEBYTECODE=1
    
    # Restart policy: restart container if it crashes
    restart: unless-stopped
    
    # Container name for easier management
    container_name: sdlc-semantic-search
    
    # Resource constraints for better compatibility
    # mem_limit: Maximum memory usage (2GB should be sufficient)
    # mem_reservation: Minimum guaranteed memory (512MB)
    mem_limit: 2g
    mem_reservation: 512m